openapi: 3.1.0
info:
  title: CorAI API
  version: 0.1.0

paths:

  /user/sign-in:
    post:
      $ref: "./user/sign-in.yaml#/sign-in"
  /user/login:
    post:
      $ref: "./user/login.yaml#/login"
  /user/logout:
    get:
      $ref: "./user/logout.yaml#/logout"
  /user/update-user/{user_id}:
    put:
      $ref: "./user/update-user.yaml#/update-user"

  /patient/get-patients:
    get:
      $ref: "./patient/get-patients.yaml#/get-patients"
  /patient/get-patient/{user_id}:
    get:
      $ref: "./patient/get-patient.yaml#/get-patient"
  /patient/update-patient-data/{user_id}:
    put:
      $ref: "./patient/update-patient-data.yaml#/update-patient-data"
  /patient/ingest/{user_id}:
    post:
      $ref: "./patient/ingest.yaml#/ingest"

  /admin/get-users:
    get:
      $ref: "./admin/get-users.yaml#/get-users"
  /admin/create-users:
    post:
      $ref: "./admin/create-users.yaml#/create-user"
  /admin/deactivate-user/{user_id}:
    put:
      $ref: "./admin/deactivate-user.yaml#/deactivate-user"
  /admin/delete-user/{user_id}:
    get:
      $ref: "./admin/delete-user.yaml#/delete-user"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

tags:
  - name: Auth 
    description: Endpoints related to authentication such as login, logout, sign in 
  - name: Admin 
    description: Endpoints related to the admin user 
  - name: User 
    description: Endpoints that apply to all users 
  - name: Doctor
    description: Endpoints related to the doctor user
  - name: Patient 
    description: Endpoints related to the patient user
